CREATE TABLE CHDRPF_STAGE (
    UNIQUE_NUMBER bigint  NOT NULL,
    CHDRPFX nchar(2)   NULL,
    CHDRCOY nchar(1)   NULL,
    CHDRNUM nchar(8)   NULL,
    RECODE nchar(2)   NULL,
    SERVUNIT nchar(2)   NULL,
    CNTTYPE nchar(3)   NULL,
    TRANNO int NULL,
    TRANID nchar(14)   NULL,
    VALIDFLAG nchar(1)   NULL,
    CURRFROM int DEFAULT 0 NOT NULL,
    CURRTO int DEFAULT 0 NOT NULL,
    PROCTRANCD nchar(4)   NULL,
    PROCFLAG nchar(2)   NULL,
    PROCID nchar(14)   NULL,
    STATCODE nchar(2)   NULL,
    STATREASN nchar(2)   NULL,
    STATDATE int NULL,
    STATTRAN int NULL,
    TRANLUSED int NULL,
    OCCDATE int NULL,
    CCDATE int NULL,
    CRDATE int NULL,
    ANNAMT01 numeric(17,2) NULL,
    ANNAMT02 numeric(17,2) NULL,
    ANNAMT03 numeric(17,2) NULL,
    ANNAMT04 numeric(17,2) NULL,
    ANNAMT05 numeric(17,2) NULL,
    ANNAMT06 numeric(17,2) NULL,
    RNLTYPE nchar(2)   NULL,
    RNLNOTS nchar(2)   NULL,
    RNLNOTTO nchar(2)   NULL,
    RNLATTN nchar(2)   NULL,
    RNLDURN int NULL,
    REPTYPE nchar(2)   NULL,
    REPNUM nchar(25)   NULL,
    COWNPFX nchar(2)   NULL,
    COWNCOY nchar(1)   NULL,
    COWNNUM nchar(8)   NULL,
    JOWNNUM nchar(8)   NULL,
    PAYRPFX nchar(2)   NULL,
    PAYRCOY nchar(1)   NULL,
    PAYRNUM nchar(8)   NULL,
    DESPPFX nchar(2)   NULL,
    DESPCOY nchar(1)   NULL,
    DESPNUM nchar(8)   NULL,
    ASGNPFX nchar(2)   NULL,
    ASGNCOY nchar(1)   NULL,
    ASGNNUM nchar(8)   NULL,
    CNTBRANCH nchar(2)   NULL,
    AGNTPFX nchar(2)   NULL,
    AGNTCOY nchar(1)   NULL,
    AGNTNUM nchar(8)   NULL,
    CNTCURR nchar(3)   NULL,
    ACCTCCY nchar(3)   NULL,
    CRATE numeric(18,9) NULL,
    PAYPLAN nchar(6)   NULL,
    ACCTMETH nchar(1)   NULL,
    BILLFREQ nchar(2)   NULL,
    BILLCHNL nchar(2)   NULL,
    COLLCHNL nchar(2)   NULL,
    BILLDAY nchar(2)   NULL,
    BILLMONTH nchar(2)   NULL,
    BILLCD int NULL,
    BTDATE int NULL,
    PTDATE int NULL,
    PAYFLAG nchar(1)   NULL,
    SINSTFROM int NULL,
    SINSTTO int NULL,
    SINSTAMT01 numeric(17,2) NULL,
    SINSTAMT02 numeric(17,2) NULL,
    SINSTAMT03 numeric(17,2) NULL,
    SINSTAMT04 numeric(17,2) NULL,
    SINSTAMT05 numeric(17,2) NULL,
    SINSTAMT06 numeric(17,2) NULL,
    INSTFROM int NULL,
    INSTTO int NULL,
    INSTBCHNL nchar(2)   NULL,
    INSTCCHNL nchar(2)   NULL,
    INSTFREQ nchar(2)   NULL,
    INSTTOT01 numeric(17,2) NULL,
    INSTTOT02 numeric(17,2) NULL,
    INSTTOT03 numeric(17,2) NULL,
    INSTTOT04 numeric(17,2) NULL,
    INSTTOT05 numeric(17,2) NULL,
    INSTTOT06 numeric(17,2) NULL,
    INSTPAST01 numeric(17,2) NULL,
    INSTPAST02 numeric(17,2) NULL,
    INSTPAST03 numeric(17,2) NULL,
    INSTPAST04 numeric(17,2) NULL,
    INSTPAST05 numeric(17,2) NULL,
    INSTPAST06 numeric(17,2) NULL,
    INSTJCTL nchar(24)   NULL,
    NOFOUTINST int NULL,
    OUTSTAMT numeric(17,2) NULL,
    BILLDATE01 int NULL,
    BILLDATE02 int NULL,
    BILLDATE03 int NULL,
    BILLDATE04 int NULL,
    BILLAMT01 numeric(17,2) NULL,
    BILLAMT02 numeric(17,2) NULL,
    BILLAMT03 numeric(17,2) NULL,
    BILLAMT04 numeric(17,2) NULL,
    FACTHOUS nchar(2)   NULL,
    BANKKEY nchar(10)   NULL,
    BANKACCKEY nchar(20)   NULL,
    DISCODE01 nchar(1)   NULL,
    DISCODE02 nchar(1)   NULL,
    DISCODE03 nchar(1)   NULL,
    DISCODE04 nchar(1)   NULL,
    GRUPKEY nchar(12)   NULL,
    MEMBSEL nchar(10)   NULL,
    APLSUPR nchar(1)   NULL,
    APLSPFROM int NULL,
    APLSPTO int NULL,
    BILLSUPR nchar(1)   NULL,
    BILLSPFROM int NULL,
    BILLSPTO int NULL,
    COMMSUPR nchar(1)   NULL,
    COMMSPFROM int NULL,
    COMMSPTO int NULL,
    LAPSSUPR nchar(1)   NULL,
    LAPSSPFROM int NULL,
    LAPSSPTO int NULL,
    MAILSUPR nchar(1)   NULL,
    MAILSPFROM int NULL,
    MAILSPTO int NULL,
    NOTSSUPR nchar(1)   NULL,
    NOTSSPFROM int NULL,
    NOTSSPTO int NULL,
    RNWLSUPR nchar(1)   NULL,
    RNWLSPFROM int NULL,
    RNWLSPTO int NULL,
    CAMPAIGN nchar(6)   NULL,
    SRCEBUS nchar(2)   NULL,
    NOFRISKS int NULL,
    JACKET nchar(8)   NULL,
    ISAM01 numeric(17,2) NULL,
    ISAM02 numeric(17,2) NULL,
    ISAM03 numeric(17,2) NULL,
    ISAM04 numeric(17,2) NULL,
    ISAM05 numeric(17,2) NULL,
    ISAM06 numeric(17,2) NULL,
    PSTCDE nchar(2)   NULL,
    PSTRSN nchar(2)   NULL,
    PSTTRN int NULL,
    PSTDAT int NULL,
    PDIND nchar(2)   NULL,
    REG nchar(3)   NULL,
    STCA nchar(3)   NULL,
    STCB nchar(3)   NULL,
    STCC nchar(3)   NULL,
    STCD nchar(3)   NULL,
    STCE nchar(3)   NULL,
    MPLPFX nchar(2)   NULL,
    MPLCOY nchar(1)   NULL,
    MPLNUM nchar(8)   NULL,
    POAPFX nchar(2)   NULL,
    POACOY nchar(1)   NULL,
    POANUM nchar(8)   NULL,
    FINPFX nchar(2)   NULL,
    FINCOY nchar(1)   NULL,
    FINNUM nchar(8)   NULL,
    WVFDAT int NULL,
    WVTDAT int NULL,
    WVFIND nchar(1)   NULL,
    CLUPFX nchar(2)   NULL,
    CLUCOY nchar(1)   NULL,
    CLUNUM nchar(8)   NULL,
    POLPLN nchar(10)   NULL,
    CHGFLAG nchar(1)   NULL,
    LAPRIND nchar(1)   NULL,
    SPECIND nchar(1)   NULL,
    DUEFLG nchar(1)   NULL,
    BFCHARGE nchar(1)   NULL,
    DISHNRCNT int NULL,
    PDTYPE nchar(1)   NULL,
    DISHNRDTE int NULL,
    STMPDTYAMT numeric(15,2) NULL,
    STMPDTYDTE int NULL,
    POLINC int NULL,
    POLSUM int NULL,
    NXTSFX int NULL,
    AVLISU nchar(1)   NULL,
    STMDTE int NULL,
    BILLCURR nchar(3)   NULL,
    TFRSWUSED int NULL,
    TFRSWLEFT int NULL,
    LASTSWDATE int NULL,
    MANDREF nchar(5)   NULL,
    CNTISS int NULL,
    CNTRCV int NULL,
    COPPN numeric(11,8) NULL,
    COTYPE nchar(1)   NULL,
    COVERNT nchar(8)   NULL,
    DOCNUM nchar(8)   NULL,
    DTECAN int NULL,
    QUOTENO nchar(8)   NULL,
    RNLSTS nchar(2)   NULL,
    SUSTRCDE nchar(4)   NULL,
    BANKCODE nchar(2)   NULL,
    PNDATE int NULL,
    SUBSFLG nchar(1)   NULL,
    HRSKIND nchar(1)   NULL,
    SLRYPFLG nchar(1)   NULL,
    TAKOVRFLG nchar(1)   NULL,
    GPRNLTYP nchar(1)   NULL,
    GPRMNTHS int NULL,
    COYSRVAC nchar(3)   NULL,
    MRKSRVAC nchar(3)   NULL,
    POLSCHPFLG nchar(1)   NULL,
    ADJDATE int NULL,
    PTDATEAB int NULL,
    LMBRNO int NULL,
    LHEADNO int NULL,
    EFFDCLDT int NULL,
    PNTRCDE nchar(4)   NULL,
    TAXFLAG nchar(1)   NULL,
    AGEDEF nchar(1)   NULL,
    TERMAGE int NULL,
    PERSONCOV nchar(1)   NULL,
    ENROLLTYP nchar(1)   NULL,
    SPLITSUBS nchar(1)   NULL,
    DTLSIND nchar(1)   NULL,
    ZRENNO int NULL,
    ZENDNO int NULL,
    ZRESNPD nchar(2)   NULL,
    ZREPOLNO nchar(20)   NULL,
    ZCOMTYP nchar(1)   NULL,
    ZRINUM nchar(16)   NULL,
    ZSCHPRT nchar(1)   NULL,
    ZPAYMODE nchar(2)   NULL,
    USRPRF nchar(10)   NULL,
    JOBNME nchar(10)   NULL,
    DATIME datetime(6) NULL,
    JOBNM nchar(10)   NULL,
    QUOTETYPE nchar(2)   DEFAULT '0' NULL,
    ZMANDREF nchar(5)   NULL,
    REQNTYPE nchar(1)   NULL,
    PAYCLT nchar(8)   NULL,
    MIDJOIN nchar(1)   NULL,
    IGRASP nchar(1)   NULL,
    IEXPLAIN nchar(1)   NULL,
    IDATE int NULL,
    CVISAIND nchar(1)   NULL,
    SUPRFLG nchar(1)   NULL,
    IENDNO numeric(3,0) NULL,
    PEIENDIND nchar(1)   NULL,
    DUEDTE int NULL,
    SCHMNO nchar(8)   NULL,
    JOBNUM int NULL,
    NLGFLG nchar(1)   NULL,
    RTGRANTEDATE int NULL,
    RTGRANTE nchar(1)   NULL,
    CPIINCRIND nchar(1)   NULL,
    SUPERFLAG nchar(1)   NULL,
    COWNNUM2 nchar(8)   NULL,
    COWNNUM3 nchar(8)   NULL,
    COWNNUM4 nchar(8)   NULL,
    COWNNUM5 nchar(8)   NULL,
    CLADD int NULL,
    REFNO nchar(10)   NULL,
    CUSTREFNUM nchar(100)   NULL,
    CONCOMMFLG nchar(1)   NULL,
    ONWEROCCUP nchar(8)   NULL
);

CREATE TABLE RISKPF_STAGE (
    UNIQUE_NUMBER bigint NOT NULL,
    RSKPFX nchar(2)   NULL,
    RSKCOY nchar(1)   NULL,
    CHDRNO nchar(8)   NULL,
    RSKNO int NULL,
    VFLAG nchar(1)   NULL,
    CNTTYP nchar(3)   NULL,
    RSKTYP nchar(3)   NULL,
    TRANNO int NULL,
    TRANID nchar(14)   NULL,
    DTEEFF int NULL,
    DTEATT int NULL,
    DTETER int NULL,
    RECFORMAT nchar(10)   NULL,
    RATFLG nchar(1)   NULL,
    SICURR nchar(3)   NULL,
    SIRAT numeric(18,9) NULL,
    TOTSI bigint NULL,
    TOTSIL bigint NULL,
    TOTPRE numeric(18,2) NULL,
    USRPRF nchar(10)   NULL,
    JOBNM nchar(10)   NULL,
    DATIME datetime(6) NULL,
    SITRGT bigint NULL,
    COPPN numeric(11,8) NULL,
    COTYPE nchar(1)   NULL
);
    




CREATE OR REPLACE PROCEDURE getSeqValue(seqName STRING)
RETURNS DOUBLE
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
    let statement = `SELECT ${SEQNAME}.nextval FROM DUAL`;
    let preparedStatement = snowflake.createStatement({sqlText:statement});
    let seqValue = preparedStatement.execute();
    seqValue.next();
    return seqValue.getColumnValue(1)
$$
  
CALL getSeqValue('ERRORLOG_SEQ');  
 
CREATE OR REPLACE PROCEDURE stage_logger(task_name STRING,logLevel STRING, Message STRING)
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
 try{
    //insert record to error log
    let task_pk = getSeqValue('ERRORLOG_SEQ');
    let insertStatement = `INSERT INTO STAGE_ERROR_LOG VALUES(${task_pk},${TASK_NAME},${ERRORMSG},'E'); `
    let resultSet = snowflake.createStatement({sqlText:insertStatement}).execute();
    resultSet.next()
    return 100;
}catch(error){
    return error
    console.log('error on log insert',error);
 }
$$


CREATE TABLE DESCPF_STAGE (
    UNIQUE_NUMBER bigint NOT NULL,
    DESCPFX nchar(2)    NULL,
    DESCCOY nchar(1)    NULL,
    DESCTABL nchar(5)    NULL,
    DESCITEM nchar(8)    NULL,
    ITEMSEQ nchar(2)    NULL,
    "LANGUAGE" nchar(1)    NULL,
    TRANID nchar(14)    NULL,
    SHORTDESC nchar(10)    NULL,
    LONGDESC nchar(30)    NULL,
    USRPRF nchar(10)    NULL,
    JOBNM nchar(10)    NULL,
    DATIME datetime(6) NULL
);

create or replace table "integralba"."DATAMART".Dim_Dates
(
DateNum number(38,0) not null,
  Date date,
  YearMonthNum number(38,0) null,
  Calendar_Quarter varchar(10) null,
  MonthNum number(10) null,
  MonthName varchar(10) null,
  MonthShortName varchar(10) null,
  WeekNum number(10) null,
  DayNumOfYear number(10) null,
  DayNumOfMonth number(10) null,
  DayNumOfWeek number(10) null,
  DayName varchar(10) null,
  DayShortName varchar(10) null,
  Quarter number(10) null,
  YearQuarterNum  number(10) null,
  DayNumOfQuarter  number(10) null,
  MonthEndDate date null,
  MonthEndIndicator varchar(1) null,
  YearNum  number(10) null)
DateNum,Date,YearMonthNum,Calendar_Quarter,MonthNum,MonthName,MonthShortName,WeekNum,DayNumOfYear,DayNumOfMonth,DayNumOfWeek,DayName,DayShortName,Quarter,YearQuarterNum,DayNumOfQuarter,MonthEndDate,MonthEndIndicator,YearNum

select * from "integralba"."DATAMART".dim_Dates